//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.27 at 12:35:53 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://web.cbr.ru/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.aguzev.firstbot.soapmodel;
